fix: remove text capital style from mew-button
MyEtherWallet/mew-components pull request #306
Opened 2022-09-16 02:38 UTC by hsurf22

remove text capital style from mew-button

![Screenshot from 2022-09-15 19-38-03](https://user-images.githubusercontent.com/9893774/190544778-e5646d00-1167-4ba4-9448-d49ff994a953.png)

2022-09-20 17:35 UTC, gamalielhere requested changes

2022-09-20 17:35 UTC, gamalielhere commented on src/components/MewButton/MewButton.vue
> +      class=""
remove unused class

2022-09-22 08:01 UTC, hsurf22 commented on src/components/MewButton/MewButton.vue
> +      class=""
fixed

2022-09-22 18:30 UTC, gamalielhere approved these changes

2022-09-22 21:05 UTC, merged